<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
        novalidate
        action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
        id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                        placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                        data-mage-init='{"mage/trim-input":{}}'
                        data-validate="{required:false, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary"
                data-trigger="trigger"
                title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                type="submit"
                aria-label="Subscribe" onclick="return false;">

                <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
            <div data-bind="mageInit: {
                    'Magento_Ui/js/modal/modal':{
                    'type': 'popup',
                    'title': '',
                    'trigger': '[data-trigger=trigger]',
                    'responsive': true,
                    'buttons': [{
                    text: jQuery.mage.__('Close'),
                    class: 'action'
                }]
                }}">
                <div class="content">
                    This is just test
                </div>
            </div>
        </form>
    </div>
</div>


